### ISSUE TITLE
yarn run hangs (angular-cli / ng build)

### ISSUE THREAD

**Issue by kemmis** [geeklearningio/gl-vsts-tasks-yarn#20] opened 2017-07-25 13:17 UTC
I have a yarn build step that runs the "build-dev-deploy" script from my package.json file.
![image](https://user-images.githubusercontent.com/647545/28573380-7928a7e4-7118-11e7-810c-7a56a3318ac8.png)
And the "build-dev-deploy" script runs "ng build --prod"
![image](https://user-images.githubusercontent.com/647545/28573536-fa54b0d8-7118-11e7-9ef8-83c1cd1798e2.png)

- This build step intermittently hangs forever... maybe about 60% of the time. Other times it executes okay... but seems to take longer than it does when I execute ng build --prod on my local machine.
- This build step works 100% of the time when I use the npm run build step instead of yarn.
- To resolve this I'm having to use yarn to install my dependencies (works great!), but then use npm to run my "build-dev-deploy" script. I'd love to use yarn instead, but it just isn't reliable right now.

Here is the execution log in case it helps:

`2017-07-24T21:52:37.7638766Z ##[section]Starting: Yarn run build-dev-deploy
2017-07-24T21:52:37.7795062Z ==============================================================================
2017-07-24T21:52:37.7795062Z Task         : Yarn task
2017-07-24T21:52:37.7795062Z Description  : Executes Yarn
2017-07-24T21:52:37.7795062Z Version      : 0.7.1001
2017-07-24T21:52:37.7795062Z Author       : Geek Learning
2017-07-24T21:52:37.7795062Z Help         : [More Information](https://github.com/geeklearningio/gl-vsts-tasks-yarn/wiki/Yarn) (Version 0.7.1001)
2017-07-24T21:52:37.7795062Z ==============================================================================
2017-07-24T21:52:38.3420124Z ##[debug]agent.workFolder=D:\2017_1_BuildAgent\_work
2017-07-24T21:52:38.3420124Z ##[debug]loading inputs and endpoints
2017-07-24T21:52:38.3420124Z ##[debug]loading ENDPOINT_AUTH_$/
2017-07-24T21:52:38.3576381Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_$/_ACCESSTOKEN
2017-07-24T21:52:38.3576381Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2017-07-24T21:52:38.3576381Z ##[debug]loading ENDPOINT_AUTH_SCHEME_$/
2017-07-24T21:52:38.3576381Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2017-07-24T21:52:38.3576381Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2017-07-24T21:52:38.3576381Z ##[debug]loading INPUT_ARGUMENTS
2017-07-24T21:52:38.3576381Z ##[debug]loading INPUT_PRODUCTIONMODE
2017-07-24T21:52:38.3576381Z ##[debug]loading INPUT_PROJECTDIRECTORY
2017-07-24T21:52:38.3576381Z ##[debug]loaded 9
2017-07-24T21:52:38.4357835Z ##[debug]Absolute path for pathSegments: D:\2017_1_BuildAgent\externals\vstsom/yarn = D:\2017_1_BuildAgent\externals\vstsom\yarn
2017-07-24T21:52:38.4357835Z ##[debug]Absolute path for pathSegments: C:\ProgramData\Oracle\Java\javapath/yarn = C:\ProgramData\Oracle\Java\javapath\yarn
2017-07-24T21:52:38.4357835Z ##[debug]Absolute path for pathSegments: C:\Windows\system32/yarn = C:\Windows\system32\yarn
2017-07-24T21:52:38.4357835Z ##[debug]Absolute path for pathSegments: C:\Windows/yarn = C:\Windows\yarn
2017-07-24T21:52:38.4357835Z ##[debug]Absolute path for pathSegments: C:\Windows\System32\Wbem/yarn = C:\Windows\System32\Wbem\yarn
2017-07-24T21:52:38.4357835Z ##[debug]Absolute path for pathSegments: C:\Windows\System32\WindowsPowerShell\v1.0\/yarn = C:\Windows\System32\WindowsPowerShell\v1.0\yarn
2017-07-24T21:52:38.4357835Z ##[debug]Absolute path for pathSegments: C:\Program Files\Microsoft SQL Server\130\Tools\Binn\/yarn = C:\Program Files\Microsoft SQL Server\130\Tools\Binn\yarn
2017-07-24T21:52:38.4357835Z ##[debug]Absolute path for pathSegments: C:\Program Files\dotnet\/yarn = C:\Program Files\dotnet\yarn
2017-07-24T21:52:38.4357835Z ##[debug]Absolute path for pathSegments: C:\Program Files\Git\cmd/yarn = C:\Program Files\Git\cmd\yarn
2017-07-24T21:52:38.4357835Z ##[debug]Absolute path for pathSegments: C:\Program Files\nodejs\/yarn = C:\Program Files\nodejs\yarn
2017-07-24T21:52:38.4357835Z ##[debug]Absolute path for pathSegments: C:\Users\svctfsapppd\AppData\Roaming\npm/yarn = C:\Users\svctfsapppd\AppData\Roaming\npm\yarn
2017-07-24T21:52:38.4357835Z ##[debug]Absolute path for pathSegments: D:\2017_1_BuildAgent\bin/yarn = D:\2017_1_BuildAgent\bin\yarn
2017-07-24T21:52:38.4357835Z ##[debug]Absolute path for pathSegments: D:\2017_1_BuildAgent\bin/yarn = D:\2017_1_BuildAgent\bin\yarn
2017-07-24T21:52:38.4357835Z ##[debug]yarn=null
2017-07-24T21:52:38.4513888Z ##[debug]Arguments=run build-dev-deploy
2017-07-24T21:52:38.4513888Z ##[debug]ProjectDirectory=D:\2017_1_BuildAgent\_work\4\s\Source\MyApp\Web Application Client
2017-07-24T21:52:38.4513888Z ##[debug]AGENT_WORKFOLDER=D:\2017_1_BuildAgent\_work
2017-07-24T21:52:38.7483374Z ##[debug]D:\2017_1_BuildAgent\_work\yarn
2017-07-24T21:52:38.7483374Z ##[debug]["dist"]
2017-07-24T21:52:38.7483374Z ##[debug]D:\2017_1_BuildAgent\_work\yarn\dist\bin\yarn.cmd
2017-07-24T21:52:38.7483374Z ##[debug]ProductionMode=false
2017-07-24T21:52:38.7483374Z ##[debug]D:\2017_1_BuildAgent\_work\yarn\dist\bin\yarn.cmd arg: run build-dev-deploy
2017-07-24T21:52:38.7483374Z ##[debug]exec tool: D:\2017_1_BuildAgent\_work\yarn\dist\bin\yarn.cmd
2017-07-24T21:52:38.7483374Z ##[debug]Arguments:
2017-07-24T21:52:38.7483374Z ##[debug]   run
2017-07-24T21:52:38.7483374Z ##[debug]   build-dev-deploy
2017-07-24T21:52:38.7483374Z [command]D:\2017_1_BuildAgent\_work\yarn\dist\bin\yarn.cmd run build-dev-deploy
2017-07-24T21:52:39.4201542Z yarn run v0.27.5
2017-07-24T21:52:39.5920321Z $ ng build --prod
2017-07-24T23:18:28.0901375Z ##[error]The operation was canceled. <-- from where I manually have to cancel the build`

**Comment by sandorfr** [comment] 2017-07-26 01:51
Hi,

Thank you for reporting this issue.

I'm afraid this is more a yarn issue than an extension issue. But as there as been several similar complaints, I'd like to find out the cause, can you provide me a minimal project which would reproduce the issue?

Kind regards

**Comment by sandorfr** [comment] 2017-07-26 01:51
Probably a duplicate of #17 btw.

**Comment by sandorfr** [comment] 2017-09-21 01:17
closing as it is a duplicate of #17

**Closed by sandorfr** 2017-09-21 01:17 UTC
Labels: duplicate, Need more information

**Comment by sandorfr** [comment] 2017-10-12 09:27
Hi @kemmis it seems that upgrading to node 8.x solves the issue please refer to : https://github.com/geeklearningio/gl-vsts-tasks-yarn/wiki/Known-Issues
