### ISSUE TITLE
Environment Variables not being passed to Node.js

### ISSUE THREAD

**Issue by Sawtaytoes** [geeklearningio/gl-vsts-tasks-yarn#54] opened 2018-10-12 02:33 UTC
Before opening an issue please [read this](https://github.com/geeklearningio/gl-vsts-tasks-yarn/wiki/How-to-Report-an-issue).

# Are you reporting a bug or a feature request ?
* [X] Bug
* [ ] Feature request

# Description

When adding environment variables to a build pipeline, they don't show up in Node.js when running a yarn command.

# Expected behavior

I should see my environment variables in `process.env`.

# Reproduction

Run a command that looks at `process.env.NODE_ENV` and set that up in the build pipeline as an environment variable.

```
MANDATORY FOR BUGS: Insert debug trace
```

*In order to allow us to quickly reproduce you issue please include a link to a reproduction repository*

# System information

**VSTS or TFS:**
* [X] VSTS
* [ ] TFS

**Agent:**
* [X] Hosted
* [ ] Custom

**OS:**
* [ ] Windows
* [ ] Mac
* [X] Linux

**Yarn version:**
1.10.1

**Node version:**
8.12.0

**Comment by sandorfr** [comment] 2018-10-12 02:36
There's this misconception that VSTS variables are environement variable but they arre not.
Btw, duplicate of #40 .

**Comment by sandorfr** [comment] 2018-10-12 03:14
Given your comment on the previous issue, I realize you might be using Yaml builds in which case you need to map the environement variable on the task itself see yaml `task` documentation: 
https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts#task

**Comment by Sawtaytoes** [comment] 2018-10-12 04:10
Thanks!

Actually, their docs told me those secret vars could be used as env vars:
> You can use agent variables as environment variabes in your scripts and as parameters in your build tasks. You cannot use them to customize the build number or to apply a version control label or tag.
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=vsts

I'd completely forgotten, but when I do builds in Docker containers, I pass them in as args too, but I can still define the environment as well using Docker's yml files. As far as I know, stuff like `NODE_ENV=production` needs to be set before running right?

Having my app accept env vars in command line arguments won't fix Webpack building all my assets in development mode.

The only way I can change the env for that task is if I use the yml format (guessing) which I'd like to avoid. The only other way is using the "Batch Script" task as it has a "Modify Environment" checkbox:
```yml
steps:
- task: BatchScript@1
  displayName: 'Run script XXXXXXXXXX'
  inputs:
    filename: XXXXXXXXXX
    modifyEnvironment: true
```
It will modify the environment variable for a given Agent Job instead of just a single task.

Is it not possible to add an "environment variables" section to the yarn task? Using Docker, I have them come in there and then grab them in my Dockerfile. All the other scripting tasks also accept Environment Variables in a separate section so that's how I'd do it with those.

I even tried a command line task with Environment Variables set to no avail:
```batch
set NODE_ENV=production && set LOCAL_DEVELOPMENT=false && yarn compile
```

**Comment by sandorfr** [comment] 2018-10-30 23:51
Would you mind providing me the yaml of your build? it's hard to understand the problem without it.

**Closed** 2018-12-15 13:30 UTC
